services:
  - type: web
    name: portfolio-backend
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
      - key: MONGODB_URI
        sync: false
